// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopAPI.Data;

#nullable disable

namespace PetShopAPI.Migrations
{
    [DbContext(typeof(PetShopDbContext))]
    partial class PetShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShopAPI.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "9b7c363d-8314-42be-bb23-463e7ac35bac",
                            Description = "Product 1 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/1/500",
                            Price = 1000L,
                            Quantity = 0,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = "bf19b623-b0f1-492a-b7cb-3e5bd8c48914",
                            Description = "Product 2 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/2/500",
                            Price = 2000L,
                            Quantity = 0,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = "42b02437-3ae6-4aa3-93bb-f234f1b5aaee",
                            Description = "Product 3 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/3/500",
                            Price = 3000L,
                            Quantity = 0,
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = "f06e4412-9f00-4b58-b911-62a94f609b88",
                            Description = "Product 4 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/4/500",
                            Price = 4000L,
                            Quantity = 0,
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = "cc4453df-e049-48eb-9df1-175c8fad325c",
                            Description = "Product 5 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/5/500",
                            Price = 5000L,
                            Quantity = 0,
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = "9a01c118-6935-418b-b57a-02f48c018515",
                            Description = "Product 6 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/6/500",
                            Price = 6000L,
                            Quantity = 0,
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = "8c4ef39a-1ed2-49c4-ad2c-84b6a9db4794",
                            Description = "Product 7 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 7000L,
                            Quantity = 0,
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = "e9a7b12d-984e-42ad-bb5b-400d68af2d86",
                            Description = "Product 8 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/8/500",
                            Price = 8000L,
                            Quantity = 0,
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = "8c992c52-3807-492d-9a50-903ea50a1296",
                            Description = "Product 9 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/9/500",
                            Price = 9000L,
                            Quantity = 0,
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = "0989e87b-9251-45e3-a4b7-47cfeb9205dc",
                            Description = "Product 10 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/10/500",
                            Price = 10000L,
                            Quantity = 0,
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = "12f8057d-4b2c-4b4d-8212-ec9c9e46ea44",
                            Description = "Product 11 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/11/500",
                            Price = 11000L,
                            Quantity = 0,
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = "192e940d-b9da-45e9-9f52-0a94101c8040",
                            Description = "Product 12 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 12000L,
                            Quantity = 0,
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = "807d8044-8a5d-4bff-b2db-eba3813aa59f",
                            Description = "Product 13 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/13/500",
                            Price = 13000L,
                            Quantity = 0,
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = "10fb21fb-7824-42e8-9e53-ec2fefbe2559",
                            Description = "Product 14 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/14/500",
                            Price = 14000L,
                            Quantity = 0,
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = "30aead17-b9e8-4855-9196-a703faee2d48",
                            Description = "Product 15 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/15/500",
                            Price = 15000L,
                            Quantity = 0,
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = "374909a2-ad58-4b0a-a655-968df4d4600c",
                            Description = "Product 16 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/16/500",
                            Price = 16000L,
                            Quantity = 0,
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = "a9f2f10a-8f44-430f-9bf9-547fe3150d08",
                            Description = "Product 17 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/17/500",
                            Price = 17000L,
                            Quantity = 0,
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = "ad30e429-842b-4167-bca5-8d3b1eaf205c",
                            Description = "Product 18 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/18/500",
                            Price = 18000L,
                            Quantity = 0,
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = "c1886aa6-48ec-4a0d-8398-6a4e2d63ccac",
                            Description = "Product 19 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/19/500",
                            Price = 19000L,
                            Quantity = 0,
                            Title = "Product 19"
                        },
                        new
                        {
                            Id = "d9026a5c-782d-4114-86c2-de772fe42f6b",
                            Description = "Product 20 description. This is an amazing product with a price-quality balance you won't find anywhere ele.",
                            ImageUrl = "https://picsum.photos/id/20/500",
                            Price = 20000L,
                            Quantity = 0,
                            Title = "Product 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
